try
    {
        console.log(x)
    }
    catch(error)
    {
        console.log(error.name,": Assign Value Of X")
    }
console.log("Darshit")